---
default: true
whitespace: false

# Grouping these, so they are out of "order"

# ==Headings==
# Heading levels should only increment by one level at a time
MD001: false

# First line in a file should be a top-level heading
MD041: false

# Heading style
MD003:
  style: "atx"
  
# Headings should be surrounded by blank lines
MD022:
  # Blank lines above and belowheading
  lines_above: 0
  lines_below: 0
  
# Multiple headings with the same content
MD024:
  # Only check sibling headings
  allow_different_nesting: true 
  
# Multiple top-level headings in the same document
MD025: 
  # Heading level and RegExp for matching title in front matter
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"
  
# Trailing punctuation in heading
MD026:
  # Punctuation characters
  punctuation: ".,;:!。，；：！"
 
# Emphasis used instead of a heading
MD036:
  # Punctuation characters
  punctuation: ".,;:!?。，；：！？"
  
# Required heading structure
MD043: false
  
# ==Lists==
# Unordered list style
MD004:
  style: "dash"

# Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2
  # Whether to indent the first level of the list
  start_indented: false
  
# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style
  style: "one_or_ordered"

# MD030/list-marker-space - Spaces after list markers
MD030:
  # Spaces for single-line unordered list items
  ul_single: 3
  # Spaces for single-line ordered list items
  ol_single: 1
  # Spaces for multi-line unordered list items
  ul_multi: 3
  # Spaces for multi-line ordered list items
  ol_multi: 1


# ==Spaces==
# Trailing spaces
MD009:
  # Spaces for line break
  br_spaces: 2
  # Allow spaces for empty lines in list items
  list_item_empty_lines: false
  # Include unnecessary breaks
  strict: false

# Hard tabs
MD010:
  # Include code blocks
  code_blocks: true

# Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 1
  
# Files should end with a single newline character
MD047: true
  
# ==Prose==
# Horizontal rule style
MD035:
  # Horizontal rule style
  style: "---"

# Line length
MD013:
  # Number of characters
  line_length: 1000
  # Number of characters for headings
  heading_line_length: 200
  # Number of characters for code blocks
  code_block_line_length: 1000
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: true

# Spaces inside emphasis markers
MD037: false

# Proper names should have the correct capitalization
MD044:
  # List of proper names
  names: [
    "API",
    "Bunkers & Badasses",
    "DnD",
    "DnD 3.5",
    "Docker",
    "Dragon",
    "Dungeons & Dragons",
    "Git",
    "GitHub",
    "JSON",
    "Markdown",
    "markdownlint",
    "Obsidian",
    "Pathfinder",
    "PF2E",
    "PF1E",
    "SSH",
    "Trello",,
    "TypeScript",
    "Ubuntu",
    "Unicorn", 
    "URL",
   "YAML",
  ]
   code_blocks: false
   html_elements: false

# Emphasis style should be consistent
MD049: 
  # Consistent Styling
  style: "consistent"
  
# Strong style should be consistent
MD050:
  # Consistent Styling
  style: "consistent"

# ==Code==
# Inline HTML
MD033:
  # Allowed elements
  allowed_elements: [<sup>]

# Spaces inside code span elements
MD038: False

# Spaces inside link text
MD039: False
  
# Fenced code blocks should have a language specified
MD040: 
  language_only: true

# Code block style
MD046:
  # Block style
  style: "fenced"

# Code fence style
MD048:
  # Code fence syle
  style: "backtick"
 
# Link fragments should be valid
MD051: true

# ==Accessibility==
# Images should have alternate text (alt text)
MD045: true

# Reference links and images should use a label that is defined
MD052: true

# Link and image reference definitions should be needed
MD053: 
  ignored_definitions: ["//"]
